image: gradle:jdk11

stages:
  - unit-tests
#  - integration-tests

unit-tests:
  script:
    - echo 'AWWWW'
#  stage: unit-tests
#  script: gradle test --tests 'epamers.surwave.unit.*'

#integration-tests:
#  stage: integration-tests
#  script: gradle test --tests 'epamers.surwave.integration.*'
