stages:
  - unit-tests
  - integration-tests

unit-tests:
  stage: unit-tests
  script: ./gradlew test --tests 'epamers.surwave.unit.*'

integration-tests:
  stage: integration-tests
  script: ./gradlew test --tests 'epamers.surwave.integration.*'
