version: '3.5'

services:
  surwave-be:
    container_name: surwave-be
    build:
      context: .
    image: surwave-be
    environment:
      - POSTGRES_DB_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - CORE_PROFILES
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - surwavenet

  db:
    container_name: db
    image: postgres:12.1-alpine
    volumes:
      - db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    networks:
      - surwavenet

networks:
  surwavenet:
    name: surwavenet

volumes:
  db: {}
