version: '3.5'

services:
  core:
    container_name: surwave
    build:
      context: .
    environment:
      - CORE_PROFILES
    networks:
      - surwave_net
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - ./db:/var/lib/postgresql
    networks:
      - surwave_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD

networks:
  surwave_net:
    driver: bridge
    name: surwave_net
