version: '3.7'

services:

  db:
    container_name: db
    image: postgres:11
    volumes:
      - ./db:/var/lib/postgresql
    networks:
      - surwave_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - surwave_net
    ports:
      - 1234:8080

networks:
  surwave_net:
    driver: bridge
    name: surwave_net
