version: '3.7'

services:
  core:
    container_name: surwave
    build:
      context: .
    networks:
      - surwave_net
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql
    networks:
      - surwave_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surwave

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - surwave_net
    ports:
      - 1234:8080

networks:
  surwave_net:
    driver: bridge
    name: surwave_net
