server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/surwave
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialize: false
