server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

  servlet:
    multipart:
      max-file-size: 10MB

app:
  upload:
    dir: data
