server:
  port: 8080

spring:
  profiles:
    active: prod
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/surwave
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialize: false

  servlet:
    multipart:
      max-file-size: 10MB

app:
  upload:
    dir: data

security:
  oauth2:
    client:
      clientId: 778041561335-u2utvmf2oc490b83m8hvhof7kirbvej3.apps.googleusercontent.com
      clientSecret: vlaz2j7bQpnj1OwmbPWiMckQ
      clientAuthenticationScheme: form
      scope: openid,email,profile
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true