server:
  port: 8080

spring:
  profiles:
    active:
      - redis-cache

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB

  redis:
    host: redis
    port: 6379
    database: 1

logging:
  level:
    root: INFO
    epamers.surwave.clients.AnalyticsClient: DEBUG

surwave:
  authType: oauth2
  s3-bucket: surwtest
  uploadDir: surwave_media
  analyticsUrl: http://surwave-analytics:5000
  cache-ttl:
    media-url: 60  #Cache TTL in minutes

security:
  oauth2:
    client:
      clientId: 778041561335-u2utvmf2oc490b83m8hvhof7kirbvej3.apps.googleusercontent.com
      clientSecret: vlaz2j7bQpnj1OwmbPWiMckQ
      clientAuthenticationScheme: form
      scope: openid,email,profile
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
